- id: vimwiki-cli
  name: Vimwiki Command-Line Interface
  description: |
    A pre-commit hook script to execute non-interactive vimwiki commands to
    rebuild tag metadata and generate links before commit. This hook relies on
    the following configuration options.
    vimwiki.options -- Extra options to pass to the vimwiki command
    vimwiki.linkspage -- Page which contains generated links
    vimwiki.taglinkspage -- Page which contains generated tag links
    vimwiki.generatelinks -- Generate links before commit (bool)
    vimwiki.generatediarylinks -- Generate diary links before commit (bool)
    vimwiki.generatetaglinks -- Generate tag links before commit (bool)
    vimwiki.rebuildtags -- Rebuild tag metadata before commit (bool)
    vimwiki.allhtml -- Convert wiki to HTML before commit (bool)
  entry: scripts/pre-commit.sh
  language: script
  require_serial: true
  types: [text]
